### ISSUE TITLE
i don't understand the lib

### ISSUE THREAD

**Issue by maxwellnewage** [txgruppi/uml.js#2]
When i run "node index.js" with my json, i have this error:

TypeError: Cannot read property 'classes' of null
    at JSONFactory.buildDiagram (C:\Users\Maxwell\git\web\uml.js\lib\factories\JSONFactory.js:44:49)
    at JSONFactory.memoized [as buildDiagram] (C:\Users\Maxwell\git\web\uml.js\node_modules\lodash\dist\lodash.js:5306:32)
    at JSONFactory.buildDocument (C:\Users\Maxwell\git\web\uml.js\lib\factories\JSONFactory.js:40:28)
    at Object.<anonymous> (C:\Users\Maxwell\git\web\uml.js\index.js:6:33)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)

Why I need the property 'classes' on my JSON?

**Comment by txgruppi** [comment]
This lib works but I didn't write any instructions on how to execute it.

You should create a definition file using the Ruby like syntax and run `uml.js ruby <file>`.

I don't really know how the f... I wanted it to work when I created this lib. I want to rewrite it but I can't do it yet.

Sorry.
